[package]
name = "Zangra"
version = "0.2.0"
authors = ["Duy"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
rand = "0.7"
chrono = "0.4"
chrono-tz = "0.5"
async-trait = "0.1"
toml = "0.5"

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["builder", "cache", "client", "framework", "gateway", "http", "model", "standard_framework", "utils", "rustls_backend", "voice"]

#[dependencies.reqwest]
#version = "0.10"
#features = ["blocking"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1"
features = ["derive"]